language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.8
install:
  - pip install -r test_requirements.txt
  - pip install .
script:
  - nosetests --with-coverage --cover-erase --cover-branches --cover-package=proxmoxer  -w tests
after_success:
  - coveralls
